// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmf0T9QzQZ2kAehYsl8pTrTAoo314bhKA',
    appId: '1:545767360728:web:67d7a6455a7cfc8e502fad',
    messagingSenderId: '545767360728',
    projectId: 'cloudmessage-5de41',
    authDomain: 'cloudmessage-5de41.firebaseapp.com',
    storageBucket: 'cloudmessage-5de41.firebasestorage.app',
    measurementId: 'G-TMT3FPW7HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbViIdrKiZ3FG3EPs5A5sXlV5hOyHalc',
    appId: '1:545767360728:android:d0482f90c9c4aa12502fad',
    messagingSenderId: '545767360728',
    projectId: 'cloudmessage-5de41',
    storageBucket: 'cloudmessage-5de41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe76eU6iu8gdC-mqqkkvEhpO0EJyACueo',
    appId: '1:545767360728:ios:31985ec1ae661ba0502fad',
    messagingSenderId: '545767360728',
    projectId: 'cloudmessage-5de41',
    storageBucket: 'cloudmessage-5de41.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe76eU6iu8gdC-mqqkkvEhpO0EJyACueo',
    appId: '1:545767360728:ios:31985ec1ae661ba0502fad',
    messagingSenderId: '545767360728',
    projectId: 'cloudmessage-5de41',
    storageBucket: 'cloudmessage-5de41.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmf0T9QzQZ2kAehYsl8pTrTAoo314bhKA',
    appId: '1:545767360728:web:3821fefd64242735502fad',
    messagingSenderId: '545767360728',
    projectId: 'cloudmessage-5de41',
    authDomain: 'cloudmessage-5de41.firebaseapp.com',
    storageBucket: 'cloudmessage-5de41.firebasestorage.app',
    measurementId: 'G-QWZST32N3N',
  );
}
